%YAML 1.2
---

#In general following settings are not used by end users but by APS Networks internal development.

PATH_PREFIX: #Various paths used in this setting file are evaluated relative to this, Default is user home diretory

BSP:
  bsp_dev: /bsp/bf-reference-bsp-9.4.0-BF2556
  # Repository path to complete BSP code.
           # Defaults to /bsp/bf-reference-bsp-<ref_bsp_version>-BF2556
           # OR /bsp/bf-reference-bsp-<ref_bsp_version>-BF6064
           # depending upon switch model selected in settings.yaml .

GB: #Following parameters are useful when you have SAL src and building it, Otherwise can be ignored.
  gb_src: /gearbox/Px-4.2_2020_03_018/work/cpss/
  gb_lib: /gearbox/Px-4.2_2020_03_018/work/cpss/compilation_root/cpss_4.2/ia64_PX/