%YAML 1.2
---

PATH_PREFIX: #Various paths used in this setting file are evaluated relative to this, Default is user home diretory

BSP: &bsp
  bsp_dev: /bsp/bf-reference-bsp-9.2.0-BF2556
  #OR
  #bsp_pkg: /bsp/bf-reference-bsp-9.2.0-BF2556

