%YAML 1.2
---

#In general following settings are not used by end users but by APS Networks internal development.

PATH_PREFIX: #Various paths used in this setting file are evaluated relative to this, Default is user home diretory

BSP: &bsp
  bsp_dev: /bsp/bf-reference-bsp-9.2.0-BF2556
  #OR
  #bsp_pkg: /bsp/bf-reference-bsp-9.2.0-BF2556

SAL: &sal
  sal_home: /sal # SAL Source directory, Param is useful for development usage only
  # Following parameters are useful when you have SAL src and building it,
  # otherwise SAL binaries are sufficient to run and following config can be ignored.
  build_third_party: true #Currently gRPC interface of SAL uses protobuf, gRPC and PI packages,
  # false - Ensure that SDE is built with p4_runtime_profile, and above mentioned deps are installed under $SDE_INSTALL
  # true - Protobuf, gRPC and PI will be built independently by AOT under $SAL_INSTALL.
  enable_grpc: true #Enables sal's grpc interface, Works only when SDE is built with p4runtime profile and selected APS profile is not stratum_xyz
  tp_install: #Path where third party SWs are installed default is SAL_HOME/install
  enable_tofino: true #Enables Tofino control in SAL, Set it false if external application wants to take over Tofino control,
  #And in case of stratum_xyz profile selected for stratum APS value is overridden to false automatically

GB: #Following parameters are useful when you have SAL src and building it, Otherwise can be ignored.
  gb_src: /Gearbox/Px-4.2_2020_03_018/work/cpss/
  gb_lib: /Gearbox/Px-4.2_2020_03_018/work/cpss/compilation_root/cpss_4.2/ia64_PX/