# Switch Types
bf2556x_1t = 'BF2556X_1T'
bf6064x_t = 'BF6064X_T'
# APS profile names
sal_hw_profile_name = 'sal_hw_profile'
sal_sim_profile_name = 'sal_sim_profile'
sde_hw_profile_name = 'sde_hw_profile'
sde_sim_profile_name = 'sde_sim_profile'
stratum_hw_profile_name = 'stratum_hw_profile'
stratum_sim_profile_name = 'stratum_sim_profile'
stratum_hw_profile = 'stratum_hw'
stratum_sim_profile = 'stratum_sim'
#p4 studio profile names
stratum_profile = 'stratum_profile'

# Env var names
switch_model_env_var_name= 'SWITCH_MODEL'
sal_home_env_var_name = 'SAL_HOME'
#sal_install_env_var_name = 'SAL_INSTALL'
tp_install_env_var_name = 'TP_INSTALL'
pythonpath_env_var_name = 'PYTHONPATH'
gb_src_home_env_var_name = 'GB_SRC_HOME'
gb_lib_home_env_var_name = 'GB_LIB_HOME'
sde_env_var_name = 'SDE'
sde_install_env_var_name = 'SDE_INSTALL'
sde_include_env_var_name = 'SDE_INCLUDE'
ld_lib_path_env_var_name = 'LD_LIBRARY_PATH'
pi_install_env_var_name = 'PI_INSTALL'
bf_sde_install_env_var_name = 'BF_SDE_INSTALL'
stratum_home_env_var_name = 'STRATUM_HOME'
stratum_config_env_var_name = 'STRATUM_CONFIG'
path_env_var_name = 'PATH'

##Yaml settings nodes
BSP_node='BSP'
ref_bsp_node='ref_bsp'
aps_bsp_pkg_node='aps_bsp_pkg'
bsp_dev_node_name='bsp_dev'
switch_model_node = 'SWITCH Model'
build_profiles_node = 'BUILD_PROFILES'
sal_home_node = 'sal_home'
sal_sw_attr_node = 'SAL'
name_node = 'name'
selected_node = 'selected'
path_prefix_node = 'PATH_PREFIX'
# SAL related nodes
sal_sim_profile_node = 'sal_sim'
sal_hw_profile_node = 'sal_hw'
details_node = 'details'
enable_grpc_node = 'enable_grpc'
enable_tofino_node = 'enable_tofino'
build_third_party_node = 'build_third_party'
tp_install_node_name = 'tp_install'
# SDE related nodes
sde_sim_profile_node = 'sde_sim'
sde_hw_profile_node = 'sde_hw'
sde_build_flags_node = 'build_flags'
sde_version_node = 'sde_version'
sde_modules_node = 'modules'
sde_details_node = 'BF SDE'
# Node value strings
sde_module_bf_kdrv_string_value = 'bf_kdrv'
sde_module_bf_kpkt_string_value = 'bf_kpkt'
