%YAML 1.2
---

#For quick start goto bottom and type in profile of choice under slected.

SWITCH Model: BF2556X_1T
#OR
#SWITCH Model: BF6064X_T

PATH_PREFIX: #Various paths used in this setting file are evaluated relative to this, Default is user home diretory

BSP: &bsp
  ref_bsp: /bsp/bf-reference-bsp-9.2.0.tar
  aps_bsp_pkg: /APS-One-touch/release/bf-reference-bsp-9.2.0-BF2556_b5c5aab.zip

BF SDE: &bf_sde
  sde_pkg: /BF/bf-sde-9.2.0.tar
  sde_home: /BF/bf-sde-9.2.0 # SDE path relative to user home. If left blank default is APS-One-touch/<bf-sde-x.y.z>.
  sde_version: 9.1.0 #Required only for running stratum, will be ignored otherwise.
  p4studio_build_profile: stratum_profile #Leave it blank to enter detailed interactive P4 Studio build shell, Value is overriden to stratum_profile in case stratum_hw_profile or stratum_sim_profile is selected
  p4_name: #Leave it blank to start SDE without a P4 program or give p4 program name which is already built in SDE. Applicable when sde_*_profile is selected from below.
  modules: #Following barefoot SDE modules will be loaded before starting SDE.
    - bf_kdrv
    #- bf_kpkt
  build_flags: #Optional list of P4Studio build flags. 
               #Provide more flags with '-' in the beginning, its for yaml syntax. 
               #and than flag e.g. '-rb'
    #- -rb
    #- -iod

STRATUM: &stratum
  stratum_home: /stratum
  stratum_config: #default is APS-One-touch/stratum_config
  mode: bsp #bsp or bsp-less ('bsp' mode is recommended)

#To quick start just type in the profile name in 'selected' with * in the beginning.
#All files and directory path are relative to user's home.
# Profile which have 'sim' in their names are meant to work on PCs in simulation mode,
# Rest are suitable for actual switches.
BUILD_PROFILES: &build_profiles

  sde_sim: &sde_sim_profile #If selected, Configure 'BF SDE' and 'BSP' node above in the file.
    name: sde_sim_profile
    details: *bf_sde
    deps:

  sde_hw: &sde_hw_profile #If selected, Configure 'BF SDE' and 'BSP' node above in the file.
    name: sde_hw_profile
    details: *bf_sde
    deps: *bsp

  sal_hw: &sal_hw_profile
    name: sal_hw_profile
    deps: *sde_hw_profile

  sal_sim: &sal_sim_profile
    name: sal_sim_profile
    deps: *sde_sim_profile

  stratum_sim: &stratum_sim_profile #If selected, Configure STRATUM node above.
    name: stratum_sim_profile
    details: *stratum
    deps: *sal_sim_profile

  stratum_hw: &stratum_hw_profile #If selected, Configure STRATUM node above.
    name: stratum_hw_profile
    details: *stratum
    deps: *sal_hw_profile

  selected: *sde_hw_profile
