%YAML 1.2
---

#For quick start goto bottom and type in profile of choice under slected.

PATH_PREFIX: #Various paths used in this setting file are evaluated relative to this, Default is user home directory

BSP:
  ref_bsp: /bsp/bf-reference-bsp-9.7.0.tgz #Reference BSP to be downloaded from Intel's support portal.
  aps_bsp_pkg: /bsp/bf-reference-bsp-9.4.0-BF2556_1.0.3.zip #Porting code for APS switch.

BF SDE:
  sde_pkg: /BF/bf-sde-9.7.0.tgz
  sde_home: /BF/bf-sde-9.7.0 #Path will be automatically created by AOT, this is SDE installation dir path (relative to PATH_PREFIX as every other path in this file). If left blank default is APS-One-touch/<bf-sde-x.y.z>.
  p4studio_build_profile: /BF/bf-sde-9.7.0/p4studio/profiles/p4-runtime-tofino.yaml
  p4_prog: #Leave it blank to start SDE without a P4 program or give p4 program name which is already built in SDE.
  modules: #Following barefoot SDE modules will be loaded before starting SDE.
    - bf_kdrv
    #- bf_kpkt

SAL :
  sal_home: /APS-One-touch/release/sal_1.3.3 #Path to directory where SAL artifacts are present
  tp_install: #3rdParty libs path to run the SAL, defaults to <sal_home>/sal_tp_install
  # If executing SAL tests configure
  dut_ips: #One or more <Switch_IP:SAL_gRPC_port> to execute SAL tests upon,
           #SAL should be running on following device address(es) before running any tests.
    - 127.0.0.1:50054
    - 10.10.192.218:50054
    - 10.10.192.219:50054


